### ISSUE TITLE
Drop down items color

### ISSUE THREAD

**Issue by ASchneiderBR** [Poeschl/slate_red#1]
Hello!

I've been using this theme for the longest time, thank you for creating it.

Do you think this can be fixed? HA has updated those select/drop down items behavior:

![image](https://user-images.githubusercontent.com/25224882/162088232-f530515f-c490-413f-bae5-256c14ecc5e1.png)

Thanks!

**Comment by Poeschl** [comment]
I will look into it, currently I have not updated my HA to the latest version, but after that a fix might be out for sure. 😉

**Comment by Poeschl** [comment]
@ASchneiderBR Should be fixed now with 1.5.0. If so, please close the issue :)

**Comment by ASchneiderBR** [comment]
Working great now! Thanks a lot!

![image](https://user-images.githubusercontent.com/25224882/164312578-ef309eb3-0dc2-47c9-b80c-39649df0cfef.png)
